language: python

python:
  - 2.7.13

matrix:
  include:
    - os: osx
      language: generic
      python:
      osx_image: xcode7.3

install:
  - ./configure
  - ./bin/pip install pytest-cov coveralls

script:
  # If debugging, use a subset of tests to reduce wait:
  # - ./bin/py.test -n 2 -vvs --cov=src/scancode tests/scancode
  - ./bin/py.test -n 2 -s --cov=src

after_success:
  - ./bin/coveralls
  - ./etc/release/release.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#aboutcode"
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: true
  template:
    - "%{repository_slug}#%{build_number} (%{branch}-%{commit}:%{author})-%{message}- %{build_url}"
